"""Central configuration for the parse-and-generate-outline pipeline."""

DEFAULT_COURSE_TITLE = "Course"
DEFAULT_DIFFICULTY = "intermediate"
DEFAULT_SOURCE_LABEL = "source"

PARSE_CONTENT_SAMPLE_CHARS = 3000
CLASSIFICATION_CONTENT_SAMPLE_CHARS = 8000

TOC_WORD_BUDGET_MIN = 8_000
TOC_WORD_BUDGET_MAX = 16_000
TOC_WORD_BUDGET_PER_ENTRY = 40

PDF_MIXED_OUTLINE_PROMPT_LIMIT = 200

MULTI_SOURCE_SLUG_PREFIX = "multi_"
