"""create job metadata tables

Revision ID: f66880bc965d
Revises: 
Create Date: 2026-04-14 17:59:04.768742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66880bc965d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('course_type', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('shared_state_blob_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('retry_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('A0', 'A1', 'S1', 'A2', 'A3', 'A4', 'A5', 'S2', 'A6', name='pipelinestep'), nullable=False),
    sa.Column('section_id', sa.String(length=128), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overrides', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='stagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_history_job_id'), 'retry_history', ['job_id'], unique=False)
    op.create_table('stage_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_id', sa.Enum('A0', 'A1', 'S1', 'A2', 'A3', 'A4', 'A5', 'S2', 'A6', name='pipelinestep'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='stagestatus'), nullable=False),
    sa.Column('validation_outcome', sa.Enum('PASS', 'WARNING', 'RECOVERABLE_FAIL', 'CRITICAL_FAIL', name='validationoutcome'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_progress_job_id'), 'stage_progress', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_progress_job_id'), table_name='stage_progress')
    op.drop_table('stage_progress')
    op.drop_index(op.f('ix_retry_history_job_id'), table_name='retry_history')
    op.drop_table('retry_history')
    op.drop_table('jobs')
    # ### end Alembic commands ###
