"""Pydantic request/response schemas for the course generation job API."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import AliasChoices, BaseModel, ConfigDict, Field


class GenerateCourseRequest(BaseModel):
    """Payload accepted by `POST /course-runs/{course_run_id}/jobs`."""

    model_config = ConfigDict(populate_by_name=True)

    requested_by: str | None = Field(
        default=None,
        max_length=255,
        description="Who requested generation; defaults to 'system' if omitted",
    )
    training_outline: dict[str, Any] | None = Field(
        default=None,
        validation_alias=AliasChoices("training_outline", "trainingOutline"),
        description=(
            "Optional Training Outline already generated by the frontend "
            "(e.g. cached from an earlier /generate-to call). When provided, "
            "TO generation is skipped and this outline is fed directly into "
            "Step 04 - Enrich Outline to produce the course spec. Accepted as "
            "either `training_outline` or `trainingOutline`."
        ),
    )


class CourseGenerationJobData(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    course_run_id: int
    status_code: str
    requested_by: str
    shared_state_blob_path: str | None
    created_at: datetime
    started_at: datetime | None
    completed_at: datetime | None
    error_message: str | None


class CourseGenerationJobResponse(BaseModel):
    """Response envelope returned right after a job is queued."""

    success: bool
    data: CourseGenerationJobData


class CancelJobResponse(BaseModel):
    """Response returned by `DELETE /jobs/{job_id}` — matches the frontend's expected shape."""

    model_config = ConfigDict(populate_by_name=True)

    job_id: str = Field(serialization_alias="jobId")
    status: str
