"""Business logic for creating and progressing course generation jobs."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from semantic_kernel import Kernel
from sqlalchemy.orm import Session

from app.core.service_bus.publisher import CourseGenerationJobPublisher
from app.models.course_generation.course_generation_job.constants import (
    JOB_STATUS_CANCELLED,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_PENDING,
    JOB_STATUS_PROCESSING,
    LOG_LEVEL_INFO,
    STAGE_A1,
)
from app.models.course_generation.course_generation_job.job import CourseGenerationJob
from app.repositories.course_basic.course_repository import CourseRepository
from app.repositories.course_generation.course_generation_job_repository import CourseGenerationJobRepository
from app.repositories.course_run.course_run_repository import CourseRunRepository
from app.repositories.course_run.course_run_spec_repository import CourseRunSpecRepository
from app.services.onboarding.course_generation.artifact_service import CourseGenerationArtifactService
from app.services.onboarding.course_generation.job_progress_service import JobProgressService
from app.services.onboarding.course_generation.training_outline_service import (
    TrainingOutlineEnrichmentError,
    TrainingOutlineValidationError,
    build_to_outline_document,
    enrich_training_outline_to_course_spec,
    validate_training_outline,
)
from app.services.onboarding.course_run.course_run_service import CourseRunNotFoundError

logger = logging.getLogger(__name__)


class JobNotCancellableError(Exception):
    """Raised when a job is already in a terminal state and cannot be cancelled."""


class CourseGenerationJobService:
    """Creates jobs, publishes their queue message, and updates their lifecycle."""

    def __init__(
        self,
        db: Session,
        publisher: CourseGenerationJobPublisher | None = None,
        kernel: Kernel | None = None,
    ) -> None:
        self.db = db
        self.repository = CourseGenerationJobRepository(db)
        self.course_run_repository = CourseRunRepository(db)
        self.course_repository = CourseRepository(db)
        self.course_run_spec_repository = CourseRunSpecRepository(db)
        self.publisher = publisher or CourseGenerationJobPublisher()
        self.kernel = kernel

    def create_and_queue(
        self,
        course_run_id: str,
        requested_by: str | None,
        training_outline: dict[str, Any] | None = None,
    ) -> CourseGenerationJob:
        """Persist a new QUEUED job for `course_run_id`, then publish its queue message.

        The job row is committed before publishing so the worker can always
        find it by `job_id`, even if it happens to pick up the message before
        this call returns.

        If `training_outline` is supplied (a TO already generated by the
        frontend), TO generation is skipped: the outline is validated, fed
        into Step 04 - Enrich Outline to produce the course spec, and both
        artifacts are uploaded to blob storage under
        `<course_title>/<job_id>/` before the job is queued.
        """
        course_run = self.course_run_repository.get_by_id(course_run_id)
        if course_run is None:
            raise CourseRunNotFoundError(f"Course run '{course_run_id}' not found.")

        job = CourseGenerationJob(
            course_run_id=course_run_id,
            status_code=JOB_STATUS_PENDING,
            requested_by=requested_by or "system",
        )
        created = self.repository.create(job)
        self.db.commit()

        # First Activity-Feed entry — the SSE stream replays it from cursor 0 as
        # soon as the client opens the pipeline view, so the feed opens with a
        # confirmed "request received" rather than a blank/"waiting" panel.
        progress = JobProgressService(self.db)
        progress.log(str(created.id), LOG_LEVEL_INFO, "Course generation request received.")
        self.db.commit()

        logger.info(
            "[course_generation] Job %s queued for course_run %s", created.id, course_run_id
        )
        logger.info(
            "[course_generation] training_outline %s in request payload for job %s (keys=%s)",
            "PRESENT" if training_outline else "ABSENT",
            created.id,
            list(training_outline.keys()) if isinstance(training_outline, dict) else None,
        )

        if training_outline is not None:
            self._process_training_outline(
                job_id=str(created.id),
                course_run_id=course_run_id,
                course_id=course_run.course_id,
                training_outline=training_outline,
            )

        self.publisher.publish(job_id=str(created.id), course_run_id=course_run_id)

        return created

    def _process_training_outline(
        self,
        *,
        job_id: str,
        course_run_id: str,
        course_id: int,
        training_outline: dict[str, Any],
    ) -> None:
        """Validate a frontend-supplied TO, enrich it via Step 04, and upload both artifacts."""
        progress = JobProgressService(self.db)
        stage_started_at = datetime.now(timezone.utc)
        try:
            if self.kernel is None:
                raise TrainingOutlineEnrichmentError(
                    "No Semantic Kernel instance available to run Step 04 enrichment."
                )

            normalized_outline = validate_training_outline(training_outline)

            course = self.course_repository.get_by_id(course_id)
            course_title = course.title if course is not None else ""
            if not course_title:
                raise TrainingOutlineEnrichmentError(
                    f"Course '{course_id}' has no title — cannot build artifact folder path."
                )

            course_spec = enrich_training_outline_to_course_spec(
                self.kernel,
                normalized_outline=normalized_outline,
                run_id=course_run_id,
                course_id=str(course_id),
                course_title=course_title,
            )

            to_outline_document = build_to_outline_document(
                job_id=job_id,
                course_id=str(course_id),
                normalized_outline=normalized_outline,
            )

            to_outline_artifact, _course_spec_artifact = CourseGenerationArtifactService(
                self.db
            ).persist_to_outline_and_course_spec(
                job_id=job_id,
                course_run_id=course_run_id,
                course_title=course_title,
                to_outline_document=to_outline_document,
                course_spec=course_spec.model_dump(),
            )

            spec_row = self.course_run_spec_repository.get_by(course_run_id=course_run_id)
            if spec_row is not None:
                spec_row.uploaded_outline_blob_path = to_outline_artifact.blob_path
                self.db.flush()
            else:
                logger.warning(
                    "[course_generation] No CourseRunSpec row for course_run_id=%s — "
                    "to_outline.json uploaded but not wired to the pipeline's read path.",
                    course_run_id,
                )

            progress.record_instant_stage(
                job_id,
                STAGE_A1,
                started_at=stage_started_at,
                completed_at=datetime.now(timezone.utc),
                log_message="Outline enriched and course spec prepared.",
            )
            self.db.commit()

            logger.info(
                "[course_generation] Training outline artifacts stored | job_id=%s course_run_id=%s "
                "blob_path=%s",
                job_id,
                course_run_id,
                to_outline_artifact.blob_path,
            )
        except (TrainingOutlineValidationError, TrainingOutlineEnrichmentError) as exc:
            self.db.rollback()
            logger.error(
                "[course_generation] Failed to process frontend-supplied training outline | "
                "job_id=%s course_run_id=%s error=%s",
                job_id,
                course_run_id,
                exc,
            )
            self.mark_failed(job_id, completed_at=None, error_message=str(exc))
            progress.fail_stage(job_id, STAGE_A1, message=str(exc))
            self.db.commit()
            raise
        except Exception as exc:
            self.db.rollback()
            logger.exception(
                "[course_generation] Unexpected error processing training outline | "
                "job_id=%s course_run_id=%s",
                job_id,
                course_run_id,
            )
            self.mark_failed(job_id, completed_at=None, error_message=str(exc))
            progress.fail_stage(job_id, STAGE_A1, message=str(exc))
            self.db.commit()
            raise

    def mark_running(self, job_id: str, *, started_at) -> CourseGenerationJob:
        job = self._get_or_raise(job_id)
        job.status_code = JOB_STATUS_PROCESSING
        job.started_at = started_at
        self.db.flush()
        return job

    def mark_completed(self, job_id: str, *, completed_at, shared_state_blob_path: str | None) -> CourseGenerationJob:
        job = self._get_or_raise(job_id)
        # A user may cancel a job while its pipeline is still running (DELETE
        # /jobs/{id} accepts a PROCESSING job). The worker runs in a separate DB
        # session and finishes the run regardless, so guard the terminal write:
        # a cancelled job must stay cancelled rather than be overwritten to
        # COMPLETED when the in-flight pipeline finishes.
        if job.status_code == JOB_STATUS_CANCELLED:
            logger.info(
                "[course_generation] Job %s was cancelled — not overwriting with COMPLETED.",
                job_id,
            )
            return job
        job.status_code = JOB_STATUS_COMPLETED
        job.completed_at = completed_at
        if shared_state_blob_path:
            job.shared_state_blob_path = shared_state_blob_path
        self.db.flush()
        return job

    def mark_failed(self, job_id: str, *, completed_at, error_message: str) -> CourseGenerationJob:
        job = self._get_or_raise(job_id)
        # See mark_completed: don't clobber a user-initiated cancellation with a
        # FAILED status when the already-running pipeline errors out afterward.
        if job.status_code == JOB_STATUS_CANCELLED:
            logger.info(
                "[course_generation] Job %s was cancelled — not overwriting with FAILED.",
                job_id,
            )
            return job
        job.status_code = JOB_STATUS_FAILED
        job.completed_at = completed_at
        job.error_message = error_message[:4000]
        self.db.flush()
        return job

    def mark_cancelled(self, job_id: str, *, completed_at) -> CourseGenerationJob:
        job = self._get_or_raise(job_id)
        if job.status_code in {JOB_STATUS_COMPLETED, JOB_STATUS_FAILED, JOB_STATUS_CANCELLED}:
            raise JobNotCancellableError(
                f"Job '{job_id}' is already {job.status_code} and cannot be cancelled."
            )
        job.status_code = JOB_STATUS_CANCELLED
        job.completed_at = completed_at
        self.db.flush()
        return job

    def _get_or_raise(self, job_id: str) -> CourseGenerationJob:
        job = self.repository.get_by_id(job_id)
        if job is None:
            raise ValueError(f"Course generation job '{job_id}' not found.")
        return job
